NOTE: Redirects are currently not supported in Windows or MacOs.
C:\Users\admin\anaconda3\envs\tfenv\lib\site-packages\torch\distributed\launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
StyleGAN2: Optimized CUDA op FusedLeakyReLU not available, using native PyTorch fallback.
StyleGAN2: Optimized CUDA op UpFirDn2d not available, using native PyTorch fallback.
StyleGAN2: Optimized CUDA op FusedLeakyReLU not available, using native PyTorch fallback.
StyleGAN2: Optimized CUDA op FusedLeakyReLU not available, using native PyTorch fallback.
StyleGAN2: Optimized CUDA op UpFirDn2d not available, using native PyTorch fallback.StyleGAN2: Optimized CUDA op FusedLeakyReLU not available, using native PyTorch fallback.

StyleGAN2: Optimized CUDA op UpFirDn2d not available, using native PyTorch fallback.
StyleGAN2: Optimized CUDA op UpFirDn2d not available, using native PyTorch fallback.
Traceback (most recent call last):
  File "C:\Users\admin\GAN2Shape\run.py", line 7, in <module>
    from gan2shape import setup_runtime, Trainer, GAN2Shape
  File "C:\Users\admin\GAN2Shape\gan2shape\__init__.py", line 3, in <module>
    from .model import GAN2Shape
  File "C:\Users\admin\GAN2Shape\gan2shape\model.py", line 17, in <module>
Traceback (most recent call last):
  File "C:\Users\admin\GAN2Shape\run.py", line 7, in <module>
    from .renderer import Renderer
  File "C:\Users\admin\GAN2Shape\gan2shape\renderer\__init__.py", line 1, in <module>
    from .renderer import Renderer
  File "C:\Users\admin\GAN2Shape\gan2shape\renderer\renderer.py", line 6, in <module>
Traceback (most recent call last):
  File "C:\Users\admin\GAN2Shape\run.py", line 7, in <module>
        from gan2shape import setup_runtime, Trainer, GAN2Shapeimport neural_renderer as nr

ModuleNotFoundError  File "C:\Users\admin\GAN2Shape\gan2shape\__init__.py", line 3, in <module>
: No module named 'neural_renderer'
Traceback (most recent call last):
  File "C:\Users\admin\GAN2Shape\run.py", line 7, in <module>
    from .model import GAN2Shape
      File "C:\Users\admin\GAN2Shape\gan2shape\model.py", line 17, in <module>
from gan2shape import setup_runtime, Trainer, GAN2Shape
  File "C:\Users\admin\GAN2Shape\gan2shape\__init__.py", line 3, in <module>
    from .model import GAN2Shape    
from .renderer import Renderer
      File "C:\Users\admin\GAN2Shape\gan2shape\model.py", line 17, in <module>
from gan2shape import setup_runtime, Trainer, GAN2Shape  File "C:\Users\admin\GAN2Shape\gan2shape\renderer\__init__.py", line 1, in <module>

  File "C:\Users\admin\GAN2Shape\gan2shape\__init__.py", line 3, in <module>
    from .renderer import Renderer    
from .model import GAN2Shape      File "C:\Users\admin\GAN2Shape\gan2shape\renderer\renderer.py", line 6, in <module>

from .renderer import Renderer
  File "C:\Users\admin\GAN2Shape\gan2shape\model.py", line 17, in <module>
  File "C:\Users\admin\GAN2Shape\gan2shape\renderer\__init__.py", line 1, in <module>
        import neural_renderer as nrfrom .renderer import Renderer

      File "C:\Users\admin\GAN2Shape\gan2shape\renderer\renderer.py", line 6, in <module>
from .renderer import RendererModuleNotFoundError
: No module named 'neural_renderer'  File "C:\Users\admin\GAN2Shape\gan2shape\renderer\__init__.py", line 1, in <module>

        import neural_renderer as nrfrom .renderer import Renderer

  File "C:\Users\admin\GAN2Shape\gan2shape\renderer\renderer.py", line 6, in <module>
ModuleNotFoundError: No module named 'neural_renderer'
    import neural_renderer as nr
ModuleNotFoundError: No module named 'neural_renderer'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2520) of binary: C:\Users\admin\anaconda3\envs\tfenv\python.exe
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\tfenv\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\anaconda3\envs\tfenv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\anaconda3\envs\tfenv\lib\site-packages\torch\distributed\launch.py", line 193, in <module>
    main()
  File "C:\Users\admin\anaconda3\envs\tfenv\lib\site-packages\torch\distributed\launch.py", line 189, in main
    launch(args)
  File "C:\Users\admin\anaconda3\envs\tfenv\lib\site-packages\torch\distributed\launch.py", line 174, in launch
    run(args)
  File "C:\Users\admin\anaconda3\envs\tfenv\lib\site-packages\torch\distributed\run.py", line 710, in run
    elastic_launch(
  File "C:\Users\admin\anaconda3\envs\tfenv\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\admin\anaconda3\envs\tfenv\lib\site-packages\torch\distributed\launcher\api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-03-17_05:04:55
  host      : MSI.ucl.ac.uk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 24384)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-03-17_05:04:55
  host      : MSI.ucl.ac.uk
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 21632)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2022-03-17_05:04:55
  host      : MSI.ucl.ac.uk
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 24592)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-03-17_05:04:55
  host      : MSI.ucl.ac.uk
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2520)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
